// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

document.querySelector("#textEditor").addEventListener("input", (function ($$event) {
        var tmp = document.querySelector("#textView");
        tmp.innerHTML = $$event.target.value;
        
      }));

document.querySelector("#textEditor").addEventListener("input", (function ($$event) {
        var tmp = document.querySelector("#textView");
        tmp.innerHTML = $$event.target.value;
        
      }));

Belt_Array.forEach([
      "#selectSmall",
      "#selectRegular",
      "#selectLarge"
    ], (function (radio_id) {
        return document.querySelector(radio_id).addEventListener("change", (function (param) {
                      var textView = document.querySelector("#textView");
                      switch (radio_id) {
                        case "#selectLarge" :
                            textView.classList = "focus:outline-none font-thin text-6xl";
                            return ;
                        case "#selectRegular" :
                            textView.classList = "focus:outline-none font-thin text-2xl";
                            return ;
                        case "#selectSmall" :
                            textView.classList = "focus:outline-none font-thin text-sm";
                            return ;
                        default:
                          return ;
                      }
                    }));
      }));

export {
  
}
/*  Not a pure module */
